import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Sobre — Sentir para Compreender", description: "Conheça o projeto, a equipe e nosso compromisso ético." };
export default function SobrePage() {
  return (
    <div className="content-container py-section"><div className="max-w-3xl mx-auto">
      <nav aria-label="Breadcrumb" className="mb-6"><ol className="flex items-center gap-2 text-sm text-[var(--color-text-dim)]"><li><Link href="/" className="hover:text-[var(--color-text)]">Início</Link></li><li aria-hidden="true">›</li><li className="text-[var(--color-text-muted)]">Sobre</li></ol></nav>
      <header className="mb-12">
        <p className="text-xs font-semibold uppercase tracking-[0.25em] text-violet-400">O projeto</p>
        <h1 className="mt-3 font-display text-heading-xl font-bold text-[var(--color-text)] sm:text-hero">Sobre o Sentir para Compreender</h1>
        <p className="mt-4 max-w-xl text-base leading-relaxed text-[var(--color-text-muted)]">Um projeto acadêmico que busca promover reflexão, empatia e conhecimento sobre avaliação psicológica inclusiva.</p>
      </header>
      <section className="mb-12"><h2 className="font-display text-2xl font-bold text-[var(--color-text)] mb-4">O que é este projeto?</h2><div className="space-y-3"><p className="text-sm leading-[1.8] text-[var(--color-text-muted)]">O &ldquo;Sentir para Compreender&rdquo; é um projeto acadêmico desenvolvido como parte da disciplina de Avaliação Psicológica. Seu objetivo é sensibilizar estudantes e profissionais sobre práticas avaliativas éticas, inclusivas e anticapacitistas.</p><p className="text-sm leading-[1.8] text-[var(--color-text-muted)]">Através de experiências imersivas, conteúdo teórico, reflexões e depoimentos, o projeto convida você a &ldquo;sentir&rdquo; as barreiras antes de &ldquo;compreender&rdquo; como superá-las.</p></div></section>
      <section className="mb-12"><div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-8"><h2 className="font-display text-xl font-bold text-amber-300 mb-4 flex items-center gap-2"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>Compromisso Ético</h2><ul className="space-y-2" role="list">{["NÃO realiza diagnóstico psicológico","NÃO substitui acompanhamento profissional","NÃO pretende representar toda experiência de pessoas com deficiência","BUSCA promover acolhimento, conscientização e reflexão ética","NÃO caricaturiza ou romantiza deficiência ou sofrimento"].map((item, i) => (<li key={i} className="flex items-start gap-2 text-sm text-amber-300/60"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="mt-0.5 flex-shrink-0 text-amber-400">{item.startsWith("NÃO") ? <><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></> : <polyline points="20,6 9,17 4,12"/>}</svg>{item}</li>))}</ul></div></section>
      <section className="mb-12"><h2 className="font-display text-2xl font-bold text-[var(--color-text)] mb-4">Equipe</h2><div className="rounded-2xl border border-[var(--color-border-subtle)] bg-[var(--color-bg-panel)] p-6"><p className="text-sm text-[var(--color-text-dim)] mb-4">Projeto desenvolvido por estudantes de Psicologia.</p><div className="space-y-3">{[{l:"Orientação",v:"[Nome do(a) Professor(a)]"},{l:"Estudantes",v:"[Nomes dos integrantes]"},{l:"Instituição",v:"[Nome da Faculdade]"}].map((x,i)=>(<div key={i} className="rounded-xl border border-[var(--color-border-subtle)] bg-[var(--color-bg)]/50 p-4"><p className="text-xs font-semibold text-violet-300 mb-1">{x.l}</p><p className="text-sm text-[var(--color-text-dim)]">{x.v}</p></div>))}</div></div></section>
      <section className="mb-12 grid gap-6 sm:grid-cols-2">
        <div className="rounded-2xl border border-[var(--color-border-subtle)] bg-[var(--color-bg-panel)] p-6"><h3 className="text-sm font-bold text-[var(--color-text)]">Contato</h3><p className="mt-2 text-xs text-[var(--color-text-dim)]">contato@sentirparacompreender.com.br</p></div>
        <div className="rounded-2xl border border-rose-500/20 bg-rose-500/5 p-6"><h3 className="text-sm font-bold text-[var(--color-text)]">Precisa de ajuda?</h3><p className="mt-2 text-xs text-[var(--color-text-dim)]">CVV: 188 (gratuita, 24h)</p></div>
      </section>
      <section className="mb-12"><h2 className="font-display text-xl font-bold text-[var(--color-text)] mb-4">Tecnologias</h2><div className="flex flex-wrap gap-2">{["Next.js","React","TypeScript","Tailwind CSS","WCAG 2.1 AA","HTML5","ARIA"].map(t=>(<span key={t} className="rounded-full border border-[var(--color-border-subtle)] bg-[var(--color-bg-panel)] px-3 py-1.5 text-xs text-[var(--color-text-dim)]">{t}</span>))}</div></section>
      <div className="mt-12 flex justify-center border-t border-[var(--color-border-subtle)] pt-8"><Link href="/" className="inline-flex items-center gap-2 rounded-full border border-[var(--color-border)] px-6 py-3 text-sm font-medium text-[var(--color-text-muted)]"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="19" y1="12" x2="5" y2="12"/><polyline points="12,19 5,12 12,5"/></svg>Voltar ao início</Link></div>
    </div></div>
  );
}
