import Link from "next/link";
import type { Experience } from "@/data/experiences";

const accentColors = {
  violet: { border: "border-l-violet-500", icon: "text-violet-400", conceptBg: "bg-violet-500/5 border-violet-500/15", stepNum: "bg-violet-500/10 text-violet-300 border-violet-500/20", tag: "bg-violet-500/10 text-violet-300 border-violet-500/20" },
  cyan: { border: "border-l-cyan-400", icon: "text-cyan-400", conceptBg: "bg-cyan-500/5 border-cyan-500/15", stepNum: "bg-cyan-500/10 text-cyan-300 border-cyan-500/20", tag: "bg-cyan-500/10 text-cyan-300 border-cyan-500/20" },
  rose: { border: "border-l-rose-400", icon: "text-rose-400", conceptBg: "bg-rose-500/5 border-rose-500/15", stepNum: "bg-rose-500/10 text-rose-300 border-rose-500/20", tag: "bg-rose-500/10 text-rose-300 border-rose-500/20" },
  amber: { border: "border-l-amber-400", icon: "text-amber-400", conceptBg: "bg-amber-500/5 border-amber-500/15", stepNum: "bg-amber-500/10 text-amber-300 border-amber-500/20", tag: "bg-amber-500/10 text-amber-300 border-amber-500/20" },
} as const;

export function ExperienceDetail({ experience }: { experience: Experience }) {
  const c = accentColors[experience.accent];
  return (
    <div className="content-container py-section">
      <div className="max-w-3xl mx-auto">
        <nav aria-label="Breadcrumb" className="mb-6"><ol className="flex items-center gap-2 text-sm text-[var(--color-text-dim)]"><li><Link href="/experiencias" className="hover:text-[var(--color-text)] transition-colors">Experiências</Link></li><li aria-hidden="true">/</li><li className="text-[var(--color-text-muted)]">{experience.title}</li></ol></nav>
        <header className="mb-10"><p className={`text-sm font-medium uppercase tracking-[0.2em] ${c.icon}`}>{experience.subtitle}</p><h1 className="mt-3 font-display text-heading-xl font-bold text-[var(--color-text)]">{experience.title}</h1><div className="mt-4 flex flex-wrap items-center gap-3"><span className={`inline-flex rounded-full border px-3 py-1 text-xs font-medium ${c.tag}`}>{experience.estimatedDuration}</span><span className={`inline-flex rounded-full border px-3 py-1 text-xs font-medium ${experience.sensoryIntensity==="alta"?"bg-rose-500/10 text-rose-300 border-rose-500/20":"bg-emerald-500/10 text-emerald-300 border-emerald-500/20"}`}>Intensidade {experience.sensoryIntensity}</span></div></header>
        {experience.contentWarning && (<div className="mb-8 flex items-start gap-3 rounded-card border border-rose-500/25 bg-rose-500/5 p-5"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="mt-0.5 flex-shrink-0 text-rose-400" aria-hidden="true"><path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg><p className="text-sm leading-relaxed text-rose-300/80">{experience.contentWarning}</p></div>)}
        <section aria-labelledby="about-h" className="mb-10"><h2 id="about-h" className="font-display text-heading font-bold text-[var(--color-text)]">Sobre esta experiência</h2><div className="mt-4 space-y-3 max-w-prose">{experience.fullDescription.map((p,i)=>(<p key={i} className="text-base leading-relaxed text-[var(--color-text-muted)]">{p}</p>))}</div></section>
        <section aria-labelledby="obj-h" className={`mb-10 border-l-4 ${c.border} pl-6`}><h2 id="obj-h" className="font-display text-heading-sm font-bold text-[var(--color-text)]">Objetivos</h2><ul className="mt-4 space-y-2" role="list">{experience.objectives.map((o,i)=>(<li key={i} className="flex items-start gap-2 text-sm leading-relaxed text-[var(--color-text-muted)]"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className={`mt-0.5 flex-shrink-0 ${c.icon}`} aria-hidden="true"><polyline points="20,6 9,17 4,12"/></svg>{o}</li>))}</ul></section>
        <section aria-labelledby="eth-h" className="mb-10"><div className="rounded-card border border-amber-500/20 bg-amber-500/5 p-5"><h2 id="eth-h" className="flex items-center gap-2 text-sm font-semibold text-amber-300"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-amber-400" aria-hidden="true"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>Nota ética</h2><p className="mt-2 text-sm leading-relaxed text-amber-300/70">{experience.ethicalNotes}</p></div></section>
        <section aria-labelledby="steps-h" className="mb-10"><h2 id="steps-h" className="font-display text-heading font-bold text-[var(--color-text)]">Roteiro</h2><ol className="mt-6 space-y-4" role="list">{experience.steps.map((s,i)=>(<li key={i} className="flex gap-4"><span className={`flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full border text-xs font-semibold ${c.stepNum}`}>{i+1}</span><div className="pt-1"><p className="text-sm leading-relaxed text-[var(--color-text-muted)]">{s.instruction}</p>{s.duration&&<span className="mt-1 inline-block text-xs text-[var(--color-text-dim)]">⏱ {s.duration}</span>}</div></li>))}</ol></section>
        <section aria-labelledby="ped-h" className="mb-10"><div className={`rounded-card border ${c.conceptBg} p-5`}><h2 id="ped-h" className="flex items-center gap-2 text-sm font-semibold text-[var(--color-text)]"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className={c.icon} aria-hidden="true"><path d="M4 19.5A2.5 2.5 0 016.5 17H20"/><path d="M4 4.5A2.5 2.5 0 016.5 2H20v20H6.5A2.5 2.5 0 014 19.5v-15z"/></svg>Conexão com a avaliação psicológica</h2><p className="mt-2 text-sm leading-relaxed text-[var(--color-text-muted)]">{experience.pedagogicalNote}</p></div></section>
        <section aria-labelledby="ref-h" className="mb-10"><h2 id="ref-h" className="font-display text-heading font-bold text-[var(--color-text)]">Para refletir</h2><ul className="mt-4 space-y-3" role="list">{experience.reflectionQuestions.map((q,i)=>(<li key={i} className="flex items-start gap-3 text-sm leading-relaxed text-[var(--color-text-muted)]"><span className={`mt-0.5 flex-shrink-0 font-bold ${c.icon}`} aria-hidden="true">?</span>{q}</li>))}</ul></section>
        <div className="flex flex-col gap-4 border-t border-[var(--color-border-subtle)] pt-8 sm:flex-row sm:justify-between"><Link href="/experiencias" className="inline-flex items-center gap-2 rounded-full border border-[var(--color-border)] px-6 py-3 text-sm font-medium text-[var(--color-text-muted)] transition-all hover:border-violet-600/40 hover:text-[var(--color-text)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-focus-ring)]"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><line x1="19" y1="12" x2="5" y2="12"/><polyline points="12,19 5,12 12,5"/></svg>Todas as experiências</Link></div>
      </div>
    </div>
  );
}
